# Generated by Django 6.0.4 on 2026-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.TextField()),
                ('dry_cleaner_name', models.CharField(max_length=200)),
                ('dry_cleaner_address', models.TextField()),
                ('blood_bank_name', models.CharField(max_length=200)),
                ('blood_bank_address', models.TextField()),
                ('canteen_name', models.CharField(max_length=200)),
                ('canteen_address', models.TextField()),
                ('second_hospital_name', models.CharField(max_length=200)),
                ('second_hospital_address', models.TextField()),
                ('ambulance_name', models.CharField(max_length=200)),
                ('ambulance_address', models.TextField()),
                ('radio_lab_name', models.CharField(max_length=200)),
                ('radio_lab_address', models.TextField()),
                ('lab_name', models.CharField(max_length=200)),
                ('lab_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
