# Generated by Django 6.0.4 on 2026-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityinformation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facility Information', 'verbose_name_plural': 'Facility Information'},
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='ambulance_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='ambulance_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='blood_bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='blood_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='canteen_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='canteen_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='dry_cleaner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='dry_cleaner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='hospital_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='lab_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='lab_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='radio_lab_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='radio_lab_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='second_hospital_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facilityinformation',
            name='second_hospital_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
