# Generated by Django 6.0.4 on 2026-08-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_facilityinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinformation',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityinformation',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MOUHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mou_type', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Signed', 'Signed'), ('Active', 'Active'), ('Expired', 'Expired')], default='Generated', max_length=30)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mou_history', to='App.facilityinformation')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
